### ISSUE TITLE
The case of the perminate inventory.

### ISSUE THREAD

**Issue by Sk8Sanctified** [sunkid/WorldModes#2]
Not sure weather this applies to Worldmode or MultiInv plugin, however I noticed the bug when I switched gamemodes to creative in a survival world the other day. What happened was I switched my modes and when I did, the inventory that was saved for the creative world also loaded with the command /gm sk8 1.. Then no matter if I killed myself or issued the command /clearinventory. This inventory would load after going through any portal. Today I installed the newest versions of both plugins, deleted all the inventory files and went to see if this would fix it. It did seem to fix the inventory from loading in every world no matter if you died or destroyed your inventory. Now the issue is, that certain saved inventory, loads everytime I go into the main world (which is also a survival world). Even if I die in that world or /clearinventory. Once I go through a portal back to that world it loads that old creative mode inventory from a few days ago... I even DELETED all the inventory files mind you before I tested the new updates of these plugins. Where in the world is this inventory coming from and why!?!?!? lol Thanks a bunch for being so patient with me. I just don't understand how this is possible anymore with a brand spanking new MultiInv. Any suggestions?

**Comment by Sk8Sanctified** [comment]
Alright I have redone a lot of my files and narrowed it down. It seems that people with the ability to change gamemodes if they do so in a world which is opposite of the mode they are switching to, it will also load the inventory which is save for that mode previously and erase the inventory you have. Also players that can /tp /home /spawn will carry over items on the rare occasion and the inventory is bugged out after that. As if there is some permanent inventory save somewhere. 

This is exactly what I did. I went from my creative world with stuff in my inventory to the main world which is survival by using /spawn,
My items carried over. Now I can empty my inventory in the main world. go back to creative and /spawn again and restore the inventory that I just emptied. Even if my inventory in creative world is empty before using /spawn

**Comment by RustyDagger** [comment]
if you ask me worldmodes just needs to stop touching the inventory and let multi inv do all the work. if you dont want to remove it from worldmodes just add a setting to turn it all off please. Multi inv was working fine at changing inv before installing this plugin.

**Comment by Sk8Sanctified** [comment]
Since 2.0 and world modes being able to restore inventory, multi inv now bugs out world modes and saves the restore or something and you will constantly get that same restore on a certain world. MultiInv hasn't been updated in a while though and is having some issues itself when people go through portals to certain worlds that they once died in. If they didn't respawn in that world after they died, there health gets saved at 0 so every time they enter they immediately die.
    What I did to solve these problems, switched over to WorldInventories to save inventory. It's doesn't have as much control of inventory being able to edit certain items and health in a yml like MultiInv, but it does the job, and does it well. It has been updated a bit more recently then MultiInv which may be why.

**Comment by sunkid** [comment]
@RustyDagger WorldModes already has a permission that will turn off inventory management: worldmodes.keep-inventory

**Comment by sunkid** [comment]
@Sk8Sanctified please pastie your permissions. Unless you have the worldmodes.keep-inventory permission, you should not be able to keep your items from a creative world. Note, that if you are using PermissionBukkit, there is an issue with player re-spawning in a survival world after death in a creative world. This is an issue with PermissionBukkit though.

**Comment by RustyDagger** [comment]
@sunkid well that is a stupid name for the node it sounds like it would still be forcing the player to keep what they had in creative.

 a setting in the config to disable all inventory related events is what is needed.

**Comment by sunkid** [comment]
Sorry you don't like the name. It does what you want though and it lets players keep their inventory from creative worlds. Not sure which part you don't understand there!?

**Comment by RustyDagger** [comment]
I dont want them to keep their inventory and i dont want this plugin to touch the inventory because it creates a large Dupe Glitch. I want all inventory Touching to be stopped by thins plugin NONE AT ALL NO copy no restore no nothing is it that hard to understand.

currently with out the permission node to keep inventory players can get items from the creative map any way by returning to the smp map and right clicking with any of the 9 hotbar slots it then returns the items from the creative inventory it fails it sucks. I want it turned off fully. uh time to find another plugin....

**Comment by sunkid** [comment]
Until you start paying me enough for support, you had better adjust your attitude, @RustyDagger. You are out of line and if you continue like this I will simply ignore you.

Two things: Upgrade to the latest version as you seem to be on 2.0 and add that permission for all players. With the worldmodes.keep-inventory WorldModes will not do any inventory management just as I stated twice above now.

**Comment by Sk8Sanctified** [comment]
PermissionsEX

groups:

```
Guest:
    default: true
    permissions:
    - modifyworld.chat
    - worldmodes.mode.*
    - essentials.rules
    - essentials.list
    - essentials.help
    options:
        rank: '1000'
    worlds:
        world:
            worldmodes.mode.creative: false
            worldmodes.mode.survival: true
        Creative:
            worldmodes.mode.creative: true
            worldmodes.mode.survival: false
        Survival:
            worldmodes.mode.creative: false
            worldmodes.mode.survival: true
        world_nether:
            worldmodes.mode.creative: false
            worldmodes.mode.survival: true
    prefix: '&3(&7Guest&3)&7'

Builder:
    default: false
    permissions:
    - modifyworld.*
    - modifyworld.chat
    - worldmodes.mode.*
    - worldmodes.drop
    - dirtpaths.*
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.back
    - essentials.back.ondeath
    - essentials.protect.entitytarget.bypass
    - essentials.afk
    - essentials.balance
    - essentials.clearinventory
    - essentials.depth
    - essentials.getpos
    - essentials.geoip.show
    - essentials.help
    - essentials.helpop
    - essentials.ignore
    - essentials.info
    - essentials.list
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.motd
    - essentials.msg
    - essentials.nick
    - essentials.pay
    - essentials.portal
    - essentials.protect
    - essentials.r
    - essentials.rules
    - essentials.seen
    - essentials.sell
    - essentials.suicide
    - essentials.worth
    - essentials.sethome.multiple
    options:
        rank: '900'
    worlds:
        world:
            worldmodes.mode.creative: false
            worldmodes.mode.survival: true
        Creative:
            worldmodes.mode.creative: true
            worldmodes.mode.survival: false
        Survival:
            worldmodes.mode.creative: false
            worldmodes.mode.survival: true
        world_nether:
            worldmodes.mode.creative: false
            worldmodes.mode.survival: true
    prefix: '&3(&eBuilder&3)&7'
```

   Kindred:
        default: false
        inheritance:
        - Builder
        permissions:
        - worldedit.chunkinfo
        - worldedit.listchunks
        - worldedit.clipboard.load
        - worldedit.clipboard.copy
        - worldedit.clipboard.flip
        - worldedit.clipboard.rotate
        - worldedit.clipboard.cut
        - worldedit.clipboard.paste
        - worldedit.clipboard.clear
        - worldedit.history.undo
        - worldedit.history.redo
        - worldedit.history.clear
        - worldedit.navigation.unstuck
        - worldedit.navigation.acscend
        - worldedit.navigation.descend
        - worldedit.navigation.ceiling
        - worldedit.navigation.thru
        - worldedit.navigation.jumpto
        - worldedit.navigation.up
        - worldedit.region.replace
        - worldedit.region.stack
        - worldedit.region.set
        - worldedit.region.overlay
        - worldedit.region.naturalize
        - worldedit.region.walls
        - worldedit.region.faces
        - worldedit.region.smooth
        - worldedit.region.move
        - worldedit.regen
        - worldedit.analysis.count
        - worldedit.selection.size
        - worldedit.selection.shift
        - worldedit.selection.expand
        - worldedit.selection.contract
        - worldedit.selection.pos
        - worldedit.selection.pos
        - worldedit.selection.hpos
        - worldedit.selection.hpos
        - worldedit.wand
        - worldedit.selection.outset
        - worldedit.selection.inset
        - worldedit.analysis.distr
        - worldedit.brush.options.size
        - worldedit.brush.options.mask
        - worldedit.superpickaxe
        - worldedit.superpickaxe.recursive
        - worldedit.superpickaxe
        - worldedit.superpickaxe.area
        - worldedit.tool.info
        - worldedit.tool.replacer
        - worldedit.tool.data-cycler
        - worldedit.tool.flood-fill
        - worldedit.brush.sphere
        - worldedit.brush.cylinder
        - worldedit.brush.clipboard
        - worldedit.brush.smooth
        - worldedit.brush.ex
        - worldedit.tool.deltree
        - worldedit.tool.farwand
        - worldedit.tool.lrbuild
        - worldedit.brush.options.material
        - worldedit.brush.options.range
        - worldedit.tool.info
        - worldedit.tool.replacer
        - worldedit.tool.data-cycler
        - worldedit.tool.flood-fill
        - worldedit.brush.sphere
        - worldedit.brush.cylinder
        - worldedit.brush.clipboard
        - worldedit.brush.smooth
        - worldedit.brush.ex
        - worldedit.tool.deltree
        - worldedit.tool.farwand
        - worldedit.tool.lrbuild
        - worldedit.remove
        - worldedit.fill
        - worldedit.fill.recursive
        - worldedit.drain
        - worldedit.fixlava
        - worldedit.fixwater
        - worldedit.removeabove
        - worldedit.removebelow
        - worldedit.removenear
        - worldedit.replacenear
        - worldedit.snow
        - worldedit.thaw
        - worldedit.green
        - worldedit.extinguish
        - essentials.warp
        - essentials.warp.list
        - essentials.sethome.multiple.vip
        options:
            rank: '800'
        prefix: '&3(&2Kindred&3)&7'

```
Moderator:
    default: false
    inheritance:
    - Kindred
    permissions:
    - worldedit.generation.cylinder
    - worldedit.generation.cylinder
    - worldedit.generation.sphere
    - worldedit.generation.sphere
    - worldedit.generation.pyramid
    - worldedit.generation.pyramid
    - worldedit.tool.tree
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.world
    - lytreehelper.generate.trees
    - lytreehelper.destroyall
    - nofloatingtrees.command.nftpurge
    - worldmodes.set.*
    - powertool
    - -modifyworld.mobtarget.*
    - nolagg.clear
    - essentials.sethome.multiple.staff
    options:
        rank: '100'
    prefix: '&3(&1Moderator&3)&7'

  Admin:
    default: false
    permissions:
    - gianttrees.*
    - gianttrees.customdangerous
    - gianttrees.custom
    - gianttrees.nolimit
    - gianttrees.reload
    - gianttrees.undoall
    - gianttrees.build
    - lytreehelper.generate.trees
    - lytreehelper.destroyall
    - lytreehelper.generate.forests
    - lytreehelper.generate.nursery
    - lytreehelper.db.blockaccess
    - lytreehelper.db.forestlist
    - lytreehelper.db.registerforest
    - lytreehelper.db.deleteforest
    - lytreehelper.db.regenerateforest
    - lagmeter.*
    - nofloatingtrees.command.nftpurge
    - essentials.sethome.multiple.unlimited
    - essentials.protect.entitytarget.bypass
    - '*'
    options:
        rank: '0'
    prefix: '&3(&4Admin&3)&7'
```

---

Those are my permissions above. The issue seems to be where inventory is restored when it doesn't need to be, happens occasionally during a command that teleports between worlds or simply going through a portal to change the world. It will save the previous world inv and then the next world you end up it. You will see the message your inventory has been restored and it will be from that previous world's inv. soooo if I add worldmodes.keep-inventory node to a the players, world modes will stop attempting to restore an inventory OR it will make it so all inventory is the same on each world...? As in, the player will put stuff in there inv from creative world then switch to survival world. Since they have the node they will keep that stuff? Because the way I understood that node works is that it ignores inventory adjustments, like separate saves. If I'm using a WorldInventories to save each worlds inventory separately, then giving the players this node will allow that plugin to do the work and worldmodes will step aside as far as inventory goes? Because if that node simply makes it so the inventory is not touch yet allows other plugins to override then that's perfect! Just what I need. If it will override the other plugin and make all inventory switches ignored then that's not so good. 

I will find out right now I guess, I know you said "retain" your inventory on the Worldmodes bukkit page. btw my bad for opening and closing the issue down there twice, I had some problems with a comment and then kept hitting close comment instead of comment to top it off. lol
